### ISSUE TITLE
Crash when no .rubocop.yml is found

### ISSUE THREAD

**Issue by jonas054** [rubocop/rubocop#132]
If I have no project `.rubocop.yml` and no `.rubocop.yml` in my home directory, I get the following:

```
jonas@jonas-laptop:~/dev4/rubocop$ ./bin/rubocop /home/jonas/.rvm/gems/ruby-1.9.3-p194/gems/journey-1.0.4/lib/journey/path/pattern.rb
/home/jonas/dev4/rubocop/lib/rubocop/cli.rb:82:in `block in inspect_file': undefined method `for_cop' for {}:Hash (NoMethodError)
    from /home/jonas/dev4/rubocop/lib/rubocop/cli.rb:80:in `each'
    from /home/jonas/dev4/rubocop/lib/rubocop/cli.rb:80:in `inspect_file'
    from /home/jonas/dev4/rubocop/lib/rubocop/cli.rb:55:in `block in run'
    from /home/jonas/dev4/rubocop/lib/rubocop/cli.rb:36:in `each'
    from /home/jonas/dev4/rubocop/lib/rubocop/cli.rb:36:in `run'
    from ./bin/rubocop:14:in `block in <main>'
    from /home/jonas/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
    from ./bin/rubocop:13:in `<main>'
```

@bolandrm I think this problem was introduced in #131.
