### ISSUE TITLE
Style/SafeNavigation crashes on Range object in RuboCop 1.75.3

### ISSUE THREAD

**Issue by pioz** [rubocop/rubocop#14112]
After updating to RuboCop `1.75.3`, I'm encountering a crash related to the `Style/SafeNavigation` cop. Here's the full error message:

```
.Scanning xxx/app/models/user.rb
An error occurred while Style/SafeNavigation cop was inspecting xxx/app/models/user.rb:541:7.
undefined method 'call_type?' for an instance of Parser::Source::Range

1 error occurred:
An error occurred while Style/SafeNavigation cop was inspecting xxx/app/models/user.rb:541:7.
configuration from xxx/.rubocop.yml
Errors are usually caused by RuboCop bugs.
Please, update to the latest RuboCop version if not already in use, and report a bug if the issue still occurs on this version.
https://github.com/rubocop/rubocop/issues
```

**RuboCop version:**  
```
1.75.3 (using Parser 3.3.8.0, Prism 1.4.0, rubocop-ast 1.44.1, analyzing as Ruby 3.4, running on ruby 3.4.2) [arm64-darwin24]
```

**Offending code:**

```ruby
if self.wise_account == 'xxx' && (
   (self.wallet.credit_currency == 'AUD' && self.country_code == 'AU') ||
   (self.wallet.credit_currency == 'CAD' && self.country_code == 'CA') ||
   (self.wallet.credit_currency == 'GBP' && self.country_code == 'GB')
 )
```

This code worked fine in previous versions (1.75.2).

Thanks!

**Comment by koic** [comment]
This issue is a dup with #14112.

**Comment by pioz** [comment]
Thanks, sorry!
