### ISSUE TITLE
[Bug] Layout/IndentationWidth: undefined method `begin_type?' for nil in v1.84.0

### ISSUE THREAD

**Issue by mfukuba** [rubocop/rubocop#14820]
## Expected behavior

RuboCop should inspect files with empty blocks without errors.

## Actual behavior

`Layout/IndentationWidth` cop crashes with `NoMethodError` when inspecting empty blocks.

## Steps to reproduce the problem

Create a file with an empty block:

```ruby
# test.rb
foo do
end
```

Run RuboCop:

```bash
rubocop test.rb
```

## Error message

```
An error occurred while Layout/IndentationWidth cop was inspecting test.rb:1:0.
/usr/local/bundle/gems/rubocop-1.84.0/lib/rubocop/cop/layout/indentation_width.rb:427:in `contains_access_modifier?': undefined method `begin_type?' for nil (NoMethodError)

          return false unless body_node.begin_type?
                                       ^^^^^^^^^^^^
```

## RuboCop version

```
1.84.0 (using Parser 3.3.10.1, Prism 1.9.0, rubocop-ast 1.49.0, analyzing as Ruby 3.3, running on ruby 3.3.10) [x86_64-linux]
```

## Notes

This regression may be related to changes in #14747, #14763, or #9373 which modified `Layout/IndentationWidth` in v1.84.0.

The issue appears to be that `body_node` can be `nil` for empty blocks, but `contains_access_modifier?` doesn't handle this case.

Suggested fix:
```ruby
return false unless body_node&.begin_type?
```

**Comment by mfukuba** [comment]
It looks like this issue has already been fixed by the following commit: https://github.com/rubocop/rubocop/commit/9bcf62fc20690940cd408de8c1917703a150c0d9

Thank you for the quick fix. Closing this issue.
