### PR TITLE
Detect empty Hash literal braces containing only newlines and spaces on `Layout/SpaceInsideHashLiteralBraces`

### PR DESCRIPTION
**Pull request by r7kamura**
I changed `Layout/SpaceInsideHashLiteralBraces` so that it can detect the following pattern as empty Hash literal braces:

```ruby
# bad
foo = {
}

# good
foo = {}
```

One reason I think this should be is that `Layout/SpaceInsideArrayLiteralBrackets` already bahaves like this.

```ruby
# bad
foo = [
]

# good
foo = []
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/space_inside_hash_literal_braces.rb [hunk 1]
```diff
@@ -60,8 +63,9 @@ module Layout
       #
       #   # good
       #   foo = { }
-      #   foo = {  }
-      #   foo = {     }
+      #   foo = {    }
```
Comment (r7kamura) [inline lib/rubocop/cop/layout/space_inside_hash_literal_braces.rb:66]: This is a trivial change to be symmetrical with the `no_space` example.

**Comment by r7kamura** [comment]
So far, there seems to be a lack of consistency in the treatment of whitespace among Layout/SpaceInside\* cops. If this pull requets is accepted, I will try to make further improvements to the other similar cops:

- `LayoutSpaceInsideArrayLiteralBrackets`
- `LayoutSpaceInsideArrayPercentLiteral`
- `LayoutSpaceInsideBlockBraces`
- `LayoutSpaceInsideHashLiteralBraces`
- `LayoutSpaceInsideParens`
- `LayoutSpaceInsidePercentLiteralDelimiters`
- `LayoutSpaceInsideRangeLiteral`
- `LayoutSpaceInsideReferenceBrackets`
- `LayoutSpaceInsideStringInterpolation`

So I would be glad to get your opinion at this time on how we should treat whitespace (should space include line break) as well.

**Comment by bbatsov** [comment]
> So I would be glad to get your opinion at this time on how we should treat whitespace (should space include line break) in this type of cops as well. In my opinion, this line break should be consistently removed in this case.

Agreed. Just an oversight on our part, as this is not a very common case. It'd be nice to make this consistent across the board for sure.

**Comment by simi** [comment]
Hello! It seems this change broke some edge case we do face. Works well with 1.36.0.

```yaml
...
Layout/SpaceInsideHashLiteralBraces: {EnforcedStyle: no_space}
...
```

```bash
bin/rubocop -d loader_spec.rb
Scanning .../loader_spec.rb
An error occurred while Layout/SpaceInsideHashLiteralBraces cop was inspecting .../loader_spec.rb:7:42.
undefined method `end_pos' for nil:NilClass                                                                                                                                                   
/home/retro/.gem/ruby/3.0.4/gems/rubocop-1.37.1/lib/rubocop/cop/layout/space_inside_hash_literal_braces.rb:197:in `range_inside_hash'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-1.37.1/lib/rubocop/cop/layout/space_inside_hash_literal_braces.rb:185:in `check_whitespace_only_hash'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-1.37.1/lib/rubocop/cop/layout/space_inside_hash_literal_braces.rb:84:in `on_hash'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-1.37.1/lib/rubocop/cop/commissioner.rb:100:in `public_send'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-1.37.1/lib/rubocop/cop/commissioner.rb:100:in `block (2 levels) in trigger_responding_cops'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-1.37.1/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'         
/home/retro/.gem/ruby/3.0.4/gems/rubocop-1.37.1/lib/rubocop/cop/commissioner.rb:99:in `block in trigger_responding_cops'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-1.37.1/lib/rubocop/cop/commissioner.rb:98:in `each'                                                                                                  
/home/retro/.gem/ruby/3.0.4/gems/rubocop-1.37.1/lib/rubocop/cop/commissioner.rb:98:in `trigger_responding_cops'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-1.37.1/lib/rubocop/cop/commissioner.rb:69:in `on_hash' 
/home/retro/.gem/ruby/3.0.4/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:158:in `block in on_send'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:155:in `each'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:155:in `each_with_index'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:155:in `on_send'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-1.37.1/lib/rubocop/cop/commissioner.rb:71:in `on_send' 
/home/retro/.gem/ruby/3.0.4/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:158:in `block in on_send'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:155:in `each'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:155:in `each_with_index'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:155:in `on_send'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-1.37.1/lib/rubocop/cop/commissioner.rb:71:in `on_send' 
/home/retro/.gem/ruby/3.0.4/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:136:in `block in on_dstr'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:136:in `each'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:136:in `on_dstr'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-1.37.1/lib/rubocop/cop/commissioner.rb:71:in `on_begin'                       
/home/retro/.gem/ruby/3.0.4/gems/rubocop-ast-1.23.0/lib/rubocop/ast/traversal.rb:157:in `on_block'
/home/retro/.gem/ruby/3.0.4/gems/rubocop-1.37.1/lib/rubocop/cop/commissioner.rb:71:in `on_block'
```

```ruby
require 'spec_helper'

describe Example do
  describe "example" do
    it "example" do
      loaded = load_configurations
      loaded['configurations'].should eql({
          "1" => 2,
          "parent_id" => nil
        } => {
          {
            "2" => 0.0.to_d,
            "parent_id" => 2
          } => {},
          {
            "2" => 0.0.to_d,
            "parent_id" => 3
          } => {}
        })
    end
  end
end
```

**Comment by koic** [comment]
@simi Thanks for your feedback. I've opened #11125.
