### ISSUE TITLE
undefined method `else_branch' for RuboCop::AST::UntilNode with Lint/ShadowingOuterLocalVariable

### ISSUE THREAD

**Issue by herwinw** [rubocop/rubocop#11184]
The following piece of code causes an error when autogenerating the config:
```ruby
def process_list(list)
  res = []

  until list.empty? # `while !list.empty?` throws the same error for WhileNode
    key = list.shift
    res << [key, 1]
  end

  if debug
    res.each do |key, value|
      p key, value # Do something with both sides
    end
  end

  res
end
```
`rubocop -d` shows the following backtrace (I limited it to the first few lines)
```
An error occurred while VariableForce cop was inspecting /opt/qnet-core/tmp/rubocop/snmp.rb.
undefined method `else_branch' for #<RuboCop::AST::UntilNode:0x0000562f1937f0c0>
vendor/bundle/ruby/2.7.0/gems/rubocop-1.39.0/lib/rubocop/cop/lint/shadowing_outer_local_variable.rb:79:in `same_conditions_node_different_branch?'
vendor/bundle/ruby/2.7.0/gems/rubocop-1.39.0/lib/rubocop/cop/lint/shadowing_outer_local_variable.rb:63:in `before_declaring_variable'
vendor/bundle/ruby/2.7.0/gems/rubocop-1.39.0/lib/rubocop/cop/force.rb:34:in `public_send'
vendor/bundle/ruby/2.7.0/gems/rubocop-1.39.0/lib/rubocop/cop/force.rb:34:in `block in run_hook'
vendor/bundle/ruby/2.7.0/gems/rubocop-1.39.0/lib/rubocop/cop/force.rb:31:in `each'
vendor/bundle/ruby/2.7.0/gems/rubocop-1.39.0/lib/rubocop/cop/force.rb:31:in `run_hook'
vendor/bundle/ruby/2.7.0/gems/rubocop-1.39.0/lib/rubocop/cop/variable_force.rb:381:in `block (2 levels) in <class:VariableForce>'
[...]
```

--------

## RuboCop version

It works fine in 1.30 - 1.35.1 (I did not check any earlier versions), broken since 1.36

```
$ [bundle exec] rubocop -V
1.39.0 (using Parser 3.1.2.1, rubocop-ast 1.23.0, running on ruby 2.7.4) [x86_64-linux-gnu]
```
