### PR TITLE
Fix an error for `Style/GuardClause` when a method call whose last argument is not a string is in the condition body

### PR DESCRIPTION
**Pull request by ydah**
This PR is fix an error for `Style/GuardClause` when a method call whose last argument is not a string is in the condition body

Prepare the following files
```ruby
# frozen_string_literal: true

def foo
  if foo?
    foo(bar)
  end
end
```

Get the following error when running RuboCop
```
bundle exec rubocop test.rb -d
For /ydah/test: configuration from /ydah/test/.rubocop.yml
configuration from /ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-performance-1.15.1/config/default.yml
configuration from /ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-performance-1.15.1/config/default.yml
Default configuration from /ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/config/default.yml
configuration from /ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-rake-0.6.0/config/default.yml
configuration from /ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-rake-0.6.0/config/default.yml
configuration from /ydah/test/config/default.yml
configuration from /ydah/test/config/default.yml
Inheriting configuration from /ydah/test/.rubocop_todo.yml
Use parallel by default.
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning /ydah/test/test.rb
An error occurred while Style/GuardClause cop was inspecting /ydah/test/test.rb:3:0.
undefined method `heredoc?' for s(:send, nil, :bar):RuboCop::AST::SendNode

          if if_branch&.send_type? && if_branch.last_argument&.heredoc?
                                                             ^^^^^^^^^^
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/style/guard_clause.rb:190:in `autocorrect'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/style/guard_clause.rb:179:in `block in register_offense'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/base.rb:346:in `correct'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/base.rb:127:in `add_offense'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/style/guard_clause.rb:176:in `register_offense'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/style/guard_clause.rb:149:in `check_ending_if'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/style/guard_clause.rb:137:in `check_ending_body'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/style/guard_clause.rb:109:in `on_def'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/commissioner.rb:100:in `public_send'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/commissioner.rb:100:in `block (2 levels) in trigger_responding_cops'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/commissioner.rb:99:in `block in trigger_responding_cops'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/commissioner.rb:98:in `each'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/commissioner.rb:98:in `trigger_responding_cops'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/commissioner.rb:69:in `on_def'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.24.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/commissioner.rb:86:in `investigate'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/team.rb:154:in `investigate_partial'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/team.rb:82:in `investigate'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/runner.rb:315:in `inspect_file'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/runner.rb:259:in `block in do_inspection_loop'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/runner.rb:293:in `block in iterate_until_no_changes'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/runner.rb:286:in `loop'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/runner.rb:286:in `iterate_until_no_changes'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/runner.rb:255:in `do_inspection_loop'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/runner.rb:138:in `block in file_offenses'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/runner.rb:163:in `file_offense_cache'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/runner.rb:137:in `file_offenses'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/runner.rb:128:in `process_file'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/runner.rb:109:in `block in each_inspected_file'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/runner.rb:108:in `each'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/runner.rb:108:in `reduce'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/runner.rb:108:in `each_inspected_file'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/runner.rb:94:in `inspect_files'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/runner.rb:47:in `run'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cli/command.rb:11:in `run'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cli/environment.rb:18:in `run'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cli.rb:72:in `run_command'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cli.rb:79:in `execute_runners'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cli.rb:48:in `run'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/exe/rubocop:19:in `block in <top (required)>'
/ydah/.rbenv/versions/3.1.2/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/exe/rubocop:19:in `<top (required)>'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bin/rubocop:25:in `load'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bin/rubocop:25:in `<top (required)>'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:58:in `load'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:58:in `kernel_load'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:23:in `run'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.13/lib/bundler/cli.rb:483:in `exec'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.13/lib/bundler/cli.rb:31:in `dispatch'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.13/lib/bundler/cli.rb:25:in `start'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.13/exe/bundle:48:in `block in <top (required)>'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.13/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.13/exe/bundle:36:in `<top (required)>'
/ydah/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/ydah/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
C

Offenses:

test.rb:4:3: C: [Correctable] Style/IfUnlessModifier: Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
  if foo?
  ^^

1 file inspected, 1 offense detected, 1 offense autocorrectable

1 error occurred:
An error occurred while Style/GuardClause cop was inspecting /ydah/test/test.rb:3:0.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop/rubocop/issues

Mention the following information in the issue report:
1.40.0 (using Parser 3.1.3.0, rubocop-ast 1.24.0, running on ruby 3.1.2) [x86_64-darwin21]
Finished in 0.6836519999997108 seconds
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [-] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/guard_clause_spec.rb [hunk 1]
```diff
@@ -83,6 +83,7 @@ def func
 
   it_behaves_like('reports offense', 'work')
   it_behaves_like('reports offense', '# TODO')
+  it_behaves_like('reports offense', 'do_something(foo)')
```
[the remark this answers is not in the document]
Comment (koic) [reply spec/rubocop/cop/style/guard_clause_spec.rb:86]: Ah, OK, I can reproduce it.

File: lib/rubocop/cop/style/guard_clause.rb [hunk 2]
```diff
@@ -187,7 +187,7 @@ def autocorrect(corrector, node, condition, replacement, guard)
           if_branch = node.if_branch
           else_branch = node.else_branch
 
-          if if_branch&.send_type? && if_branch.last_argument&.heredoc?
+          if if_branch&.send_type? && here_doc?(if_branch.last_argument)
```
Comment (koic) [inline lib/rubocop/cop/style/guard_clause.rb:190]:
```suggestion
          if if_branch&.send_type? && heredoc?(if_branch.last_argument)
```

File: lib/rubocop/cop/style/guard_clause.rb [hunk 3]
```diff
@@ -201,6 +201,10 @@ def autocorrect(corrector, node, condition, replacement, guard)
         end
         # rubocop:enable Metrics/AbcSize, Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
 
+        def here_doc?(argument)
```
Comment (koic) [inline lib/rubocop/cop/style/guard_clause.rb:204]:
```suggestion
        def heredoc?(argument)
```

File: lib/rubocop/cop/style/guard_clause.rb [hunk 4]
```diff
@@ -201,6 +201,10 @@ def autocorrect(corrector, node, condition, replacement, guard)
...
+          argument&.str_type? && argument&.heredoc?
```
Comment (koic) [inline lib/rubocop/cop/style/guard_clause.rb:205]:
```suggestion
          argument&.str_type? && argument.heredoc?
```

File: lib/rubocop/cop/style/guard_clause.rb [hunk 5]
```diff
@@ -201,6 +201,12 @@ def autocorrect(corrector, node, condition, replacement, guard)
         end
         # rubocop:enable Metrics/AbcSize, Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
 
+        def heredoc?(argument)
+          return false if argument.nil?
+
+          argument.str_type? && argument.heredoc?
```
Comment (koic) [inline lib/rubocop/cop/style/guard_clause.rb:207]: I think the following patch is required to prevent a regression. Can you confirm and update it?

```diff
diff --git a/lib/rubocop/cop/style/guard_clause.rb b/lib/rubocop/cop/style/guard_clause.rb
index cfa80b912..5b2b7d4e1 100644
--- a/lib/rubocop/cop/style/guard_clause.rb
+++ b/lib/rubocop/cop/style/guard_clause.rb
@@ -204,7 +204,7 @@ module RuboCop
         def heredoc?(argument)
           return false if argument.nil?

-          argument.str_type? && argument.heredoc?
+          argument.respond_to?(:heredoc?) && argument.heredoc?
         end

         def autocorrect_heredoc_argument(corrector, node, heredoc_branch, leave_branch, guard)
diff --git a/spec/rubocop/cop/style/guard_clause_spec.rb b/spec/rubocop/cop/style/guard_clause_spec.rb
index 3f70ddc06..c3743b139 100644
--- a/spec/rubocop/cop/style/guard_clause_spec.rb
+++ b/spec/rubocop/cop/style/guard_clause_spec.rb
@@ -297,6 +297,32 @@ RSpec.describe RuboCop::Cop::Style::GuardClause, :config do
     RUBY
   end

+  it 'registers an offense when using xstr heredoc as an argument of raise in `else` branch' do
+    expect_offense(<<~RUBY)
+      def func
+        unless condition
+        ^^^^^^ Use a guard clause (`raise <<~`MESSAGE` unless condition`) instead of wrapping the code inside a conditional expression.
+          raise <<~`MESSAGE`
+            oops
+          MESSAGE
+        else
+          foo
+        end
+      end
+    RUBY
+
+    # NOTE: Let `Layout/HeredocIndentation`, `Layout/ClosingHeredocIndentation`, and
+    #       `Layout/IndentationConsistency` cops autocorrect inconsistent indentations.
+    expect_correction(<<~RUBY)
+      def func
+        raise <<~`MESSAGE` unless condition
+            oops
+          MESSAGE
+      foo
+      end
+    RUBY
+  end
+
   context 'MinBodyLength: 1' do
     let(:cop_config) { { 'MinBodyLength' => 1 } }
```

Comment (ydah) [reply lib/rubocop/cop/style/guard_clause.rb:207]: Looks good! I'll fix it right away.

**Comment by ydah** [comment]
@koic Appreciate the prompt review. Thank you so much!

**Comment by mathieujobin** [comment]
Is this included in 1.40 ?

Because I have just started having this problem...

**Comment by koic** [comment]
@mathieujobin This patch has not yet been released.

**Comment by inkstak** [comment]
This error has been fixed in some cases after upgrading to 1.41, but there are still the same error in the following case:

```ruby
def method
  # do something
rescue SomeException => e
  if should_retry?
    retry
  else
    raise e
  end
end
```

```
bundle exec rubocop test.rb -d
For [path] configuration from [path]/.rubocop.yml
Inheriting configuration from [path]/.rubocop_todo.yml
Use parallel by default.
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning [path]/test.rb
undefined method `heredoc?' for s(:lvar, :e):RuboCop::AST::Node
/Users/ink/.rvm/gems/ruby-2.7.6@mon-territoire/gems/rubocop-1.41.0/lib/rubocop/cop/style/guard_clause.rb:192:in `autocorrect'
/Users/ink/.rvm/gems/ruby-2.7.6@mon-territoire/gems/rubocop-1.41.0/lib/rubocop/cop/style/guard_clause.rb:179:in `block in register_offense'
/Users/ink/.rvm/gems/ruby-2.7.6@mon-territoire/gems/rubocop-1.41.0/lib/rubocop/cop/base.rb:362:in `correct'
/Users/ink/.rvm/gems/ruby-2.7.6@mon-territoire/gems/rubocop-1.41.0/lib/rubocop/cop/base.rb:126:in `add_offense'
/Users/ink/.rvm/gems/ruby-2.7.6@mon-territoire/gems/rubocop-1.41.0/lib/rubocop/cop/style/guard_clause.rb:176:in `register_offense'
/Users/ink/.rvm/gems/ruby-2.7.6@mon-territoire/gems/rubocop-1.41.0/lib/rubocop/cop/style/guard_clause.rb:128:in `on_if'
/Users/ink/.rvm/gems/ruby-2.7.6@mon-territoire/gems/rubocop-1.41.0/lib/rubocop/cop/commissioner.rb:101:in `public_send'
[...]
1 file inspected, no offenses detected
An error occurred while Style/GuardClause cop was inspecting /[path]/test.rb:27:6.

1 error occurred:
An error occurred while Style/GuardClause cop was inspecting [path]/test.rb:27:6.
```

For some reasons, inverting the condition doesn't raise an exception: 

```ruby 
def method
  # do_something
rescue SomeException => e
  if should_not_retry?
    raise e
  else
    retry
  end
end
```
