### PR TITLE
Fix `Layout/SpaceInsideArrayLiteralBrackets` cop error on array pattern without brackets

### PR DESCRIPTION
**Pull request by viralpraxis**
Array pattern might have no brackets:

```bash
$ echo 'case a; in a, b, _; end' | bundle exec rubocop --only Layout/SpaceInsideArrayLiteralBrackets --stdin bug.rb -d
An error occurred while Layout/SpaceInsideArrayLiteralBrackets cop was inspecting bug.rb:1:11.
undefined method '+' for nil
lib/rubocop/cop/layout/space_inside_array_literal_brackets.rb:132:in 'RuboCop::Cop::Layout::SpaceInsideArrayLiteralBrackets#next_to_newline?'
rubocop/cop/layout/space_inside_array_literal_brackets.rb:95:in 'RuboCop::Cop::Layout::SpaceInsideArrayLiteralBrackets#on_array'
```

This bug was introduced in https://github.com/rubocop/rubocop/pull/14144

-----------------

Before submitting the PR make sure the following are checked:

* [X] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [X] Wrote [good commit messages][1].
* [X] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [X] Feature branch is up-to-date with `master` (if not - rebase it).
* [X] Squashed related commits together.
* [X] Added tests.
* [X] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [X] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by etiennebarrie** [comment]
I'm seeing the same exception.

**Comment by koic** [comment]
Thanks!

**Comment by bkuhlmann** [comment]
Thanks for the quick fix! Any chance a patch release could be pushed out as this is killing a lot of my CI builds due to this exception.
